### ISSUE TITLE
Add support for BTreeSet?

### ISSUE THREAD

**Issue by droundy** [corpus-tools/graphannis-malloc_size_of#1]
I'd love to be able to apply this to BTreeSet (and BTreeMap).

**Comment by thomaskrause** [comment]
I used the following code in another project to estimate the BTreeMap size which works reasonable well for my purposes, but is not actually accurate because the overhead for the nodes is not included.

```rust
pub fn size_of_btreemap<K, V>(
    val: &std::collections::BTreeMap<K, V>,
    ops: &mut MallocSizeOfOps,
) -> usize
where
    K: MallocSizeOf,
    V: MallocSizeOf,
{
    // FIXME: Overhead for the BTreeMap nodes is not accounted for.
    let mut size = 0;
    for (key, value) in val.iter() {
        size += std::mem::size_of::<(K, V)>() + key.size_of(ops) + value.size_of(ops);
    }
    size
}
```
Since it is not accurate, I am feeling a bit uneasy with releasing a version which is known not to be accurate.

When using the `#[derive(MallocSizeOf)` macro of the [graphannis-malloc_size_of_derive](https://github.com/korpling/graphannis-malloc_size_of_derive) crate the function can be used to estimate the size for fields by using the [with_malloc_size_of_func](https://github.com/korpling/graphannis-malloc_size_of_derive#with_malloc_size_of_func-field-attribute) field attribute.
